### PR TITLE
Guzzle: update to v7

### PR DESCRIPTION
**Pull request by davidrans**
Onward and upward

cr_req 1

### CODE REVIEW

**Comment by scbarber** [comment]
The changeset is easy to review 😂 but are there implications in the major version bump? https://github.com/guzzle/guzzle/blob/7.0.0/UPGRADING.md#60-to-70 lists backwards compatibility breaking changes. Off-hand, do you know if any of those pose a problem to our Guzzle use?

**Comment by sctice** [comment]
After many trials and tribulations, I finally got [a branch on `ifixit/ifixit` updated to this version](https://github.com/iFixit/ifixit/compare/guzzle--test-upgrade-to-7?expand=1), with the latest Guzzle (7.2) and updates to all of the other packages that depend on Guzzle. See the commit on that branch for the necessary changes to `composer.json` and the command that finally did the trick (without updating _everything_).

After doing that, I ran a script that I have sitting around that uses this library to perform some requests against the sandbox API. Here's that script, for posterity:

[01-active-campaign.php.txt](https://github.com/iFixit/activecampaign-v3-php/files/5817821/01-active-campaign.php.txt)

That seemed to be communicating just fine with the API. I then went ahead and did some grepping for the Guzzle interfaces affected by the upgrade. Here's a curated list of the things I looked for (under `vendor/mediatoolkit/activecampaign-v3-php`):

```
 rg Guzzle
 # …Only a few uses of \GuzzleHttp\Client, unaffected by changes

 rg "[\"'](exception|save_to|pool_size)"
 # …Nothing (looking for affected options)

 rg exception
 # …Nothing(?!)
 rg Exception
 # …Yep, still nothing; `rg` is case-insensitive by default

 rg extends
 # …Nothing extending Guzzle classes
```

So I'm pretty confident that this code is fine with the latest Guzzle. However, there are still a few dependencies over on `ifixit/ifixit` that need to be updated in order to update Guzzle there. If we merge this change into master, I'm concerned that composer in `ifixit/ifixit` will complain about requiring `guzzle 7.2`.

QA :flags: but deploy_block :hand: on figuring out the update path.

P.S.: I did a test suite run against that branch with Guzzle 7.2, and it's hitting [issues with updated  `promphp/prometheus_client_php`](https://www.ubreakit.com/Misc/cimpler-logs/ifixit/guzzle-test-upgrade-to-7--225f5dea1c4403c857cdc550ddf7d42eaae23b1f--1610673459351.log) (hit maximum 20 failed tests) and [a few Psalm errors in our app `ActiveCampaign` code](https://www.ubreakit.com/Misc/cimpler-logs/psalm/guzzle-test-upgrade-to-7--225f5dea1c4403c857cdc550ddf7d42eaae23b1f--1610673789811.log) (not code from this library) caused by updated Guzzle types.

**Comment by davidrans** [comment]
>  I did a test suite run against that branch with Guzzle 7.2, and it's hitting [issues with updated `promphp/prometheus_client_php`](https://www.ubreakit.com/Misc/cimpler-logs/ifixit/guzzle-test-upgrade-to-7--225f5dea1c4403c857cdc550ddf7d42eaae23b1f--1610673459351.log) (hit maximum 20 failed tests)

I'm working on that here: https://github.com/iFixit/ifixit/pull/35846

**Comment by BaseInfinity** [comment]
CR 👙  but deploy_block 👙  for obvious reasons (pull open to address prometheus)

**Comment by davidrans** [comment]
Is it safe to merge this now, as long as we wait to update to the newest version in the main repo?

**Comment by sctice** [comment]
> Is it safe to merge this now, as long as we wait to update to the newest version in the main repo?

I don't _think_ so, unless we change the way we specify this dependency in the main repo. My reasoning is that the main repo depends on `dev-master` for this package, so as soon as we merge this to `master`, satisfying composer dependencies in the main repo is going to require satisfying the new dependency on Guzzle 7, which it can't do.

**Comment by davidrans** [comment]
But in the `composer.lock` there's a particular commit specified, right? For example, we had to manually update `statsd-php-client`: https://github.com/iFixit/ifixit/pull/35842

**Comment by sctice** [comment]
> But in the `composer.lock` there's a particular commit specified, right? For example, we had to manually update `statsd-php-client`: [iFixit/ifixit#35842](https://github.com/iFixit/ifixit/pull/35842)

Cool, I think you're right then, and merging this should be fine. I double-checked the docs:

> Either way, running install when a composer.lock file is present resolves and installs all dependencies that you listed in composer.json, but Composer uses the exact versions listed in composer.lock to ensure that the package versions are consistent for everyone working on your project. As a result you will have all dependencies requested by your composer.json file, but they may not all be at the very latest available versions (some of the dependencies listed in the composer.lock file may have released newer versions since the file was created). This is by design, it ensures that your project does not break because of unexpected changes in dependencies.

I also double-checked that `statsd-php-client` is also requesting `dev-master`. It appears that the procedure above holds for `dev-master` files (I guess using commit hashes) as well as versioned packages.

un_deploy_block :flags:

**Pull request merged**
